export const hairdressingDictionnaryEN = {
  "Coupe de cheveux": "Haircut",
  "Rafraîchir les pointes": "Trim",
  "Brushing": "Blow-dry",
  "Dégradé": "Layers",
  "Frange": "Bangs",
  "Mèches claires": "Highlights",
  "Teindre": "Dye",
  "Lisser": "Straighten",
  "Bouclé": "Curly",
  "Épais": "Thick",
  "Fin": "Thin",
  "Brosse à cheveux": "Hairbrush",
  "Shampoing": "Shampoo",
  "Rendez-vous": "Appointment",
  "Patine": "Gloss",
  "Blonde": "Blonde",
  "Brune": "Brunette",
  "Cheveux châtains": "Brown hair",
  "Cheveux noirs": "Black hair",
  "Cheveux roux": "Red hair",
  "Cheveux auburn": "Auburn hair",
  "Cheveux gris": "Grey hair",
  "Cheveux blancs": "White hair",
  "Brun foncé": "Dark brown",
  "Châtain clair": "Light brown",
  "Blond clair": "Light blonde",
  "Blond platine": "Platinum blonde",
  "Blond cendré": "Ash blonde",
  "Blond doré": "Golden blonde",
  "Blond vénitien": "Strawberry blonde",
  "Cheveux teints": "Dyed hair",
  "Cheveux colorés": "Coloured hair",
  "Cheveux naturels": "Natural hair",
  "Mèches foncées": "Lowlights",
  "Racines": "Roots",
  "Retouche des racines": "Root touch-up",
  "Balayage": "Balayage",
  "Ombré": "Ombre",
  "Coloration complète": "Full head colour",
  "Coloration des pointes": "Dip-dye",
  "Correcteur de reflet": "Toner",
  "Tons cendrés": "Ashy tones",
  "Tons chauds": "Warm tones",
  "Tons froids": "Cool tones",
  "Cuivré": "Copper",
  "Caramel": "Caramel",
  "Châtain noisette": "Chestnut brown",
  "Cheveux courts": "Short hair",
  "Cheveux mi-longs": "Medium-length hair",
  "Cheveux longs": "Long hair",
  "Cheveux jusqu'aux épaules": "Shoulder-length hair",
  "Cheveux jusqu'au menton": "Chin-length hair",
  "Cheveux jusqu'à la mâchoire": "Jaw-length hair",
  "Cheveux très courts": "Very short hair",
  "Coupe rasée": "Buzz cut",
  "Carré": "Bob cut",
  "Cheveux dégradés": "Layered hair",
  "Pointes coupées": "Trimmed ends",
  "Cheveux qui ont repoussé": "Grown-out hair",
  "Cheveux épais": "Thick hair",
  "Cheveux fins": "Thin hair",
  "Cheveux plats": "Flat hair",
  "Cheveux volumineux": "Voluminous hair",
  "Cheveux lourds": "Heavy hair",
  "Cheveux légers": "Light hair",
  "Cheveux bouclés": "Curly hair",
  "Cheveux crépus / très frisottés": "Frizzy hair",
  "Cheveux très fins": "Fine hair",
  "Cheveux denses": "Dense hair",
  "Cheveux clairsemés": "Sparse hair",
  "Cheveux gras": "Oily hair",
  "Cheveux secs": "Dry hair",
  "Cheveux abîmés": "Damaged hair",
  "Coupe très courte": "Pixie cut",
  "Coupe courte homme": "Crew cut",
  "Coupe dégradée": "Layered cut",
  "Coupe droite": "Blunt cut",
  "Carré long": "Lob (long bob)",
  "Rasé sur les côtés": "Undercut",
  "Dégradé progressif": "Fade",
  "Raie sur le côté": "Side part",
  "Raie au milieu": "Middle part",
  "Queue de cheval": "Ponytail",
  "Tresse": "Braid",
  "Tresse française": "French braid",
  "Natte / Tresse": "Plait (UK)",
  "Coiffure relevée": "Updo",
  "Chignon": "Bun",
  "Chignon décoiffé": "Messy bun",
  "Cheveux lissés": "Straightened hair",
  "Cheveux ondulés": "Wavy hair",
  "Coiffé vers l'arrière": "Brushed back",
  "Plaqué vers l'arrière": "Slicked back",
  "Couper": "Cut",
  "Faire un shampoing": "Shampoo (v)",
  "Rincer": "Rinse",
  "Faire un brushing": "Blow-dry (v)",
  "Boucler": "Curl",
  "Dégrader": "Layer",
  "Décolorer": "Bleach",
  "Corriger les reflets": "Tone",
  "Coiffer": "Style",
  "Brosser": "Brush",
  "Peigner": "Comb (v)",
  "Laver": "Wash",
  "Sécher": "Dry",
  "Vouloir": "Want",
  "Aimer": "Like",
  "Préférer": "Prefer",
  "Avoir besoin": "Need",
  "Aimerais": "Would like",
  "Attacher les cheveux": "Tie up",
  "Détacher les cheveux": "Let down",
  "Changer": "Change",
  "Garder": "Keep",
  "Laisser tel quel": "Leave",
  "Raccourcir": "Shorten",
  "Foncer les cheveux": "Go darker",
  "Éclaircir les cheveux": "Go lighter",
  "Couvrir les cheveux blancs": "Cover the grey",
  "Faire une retouche": "Touch up",
  "Recolorer": "Recolour",
  "Essayer une nouvelle nuance": "Try a new shade",
  "Entretenir la couleur": "Maintain the colour",
  "Laisser repousser la couleur": "Let it grow out",
  "Raviver la teinte": "Enhance the tone",
  "Raviver la couleur": "Refresh the colour",
  "Rattraper une couleur ratée": "Fix the colour",
  "Uniformiser la couleur": "Even out the colour",
  "Fondre la couleur avec les racines": "Blend with the roots",
  "Après-shampoing": "Conditioner",
  "Masque capillaire": "Hair mask",
  "Soin sans rinçage": "Leave-in conditioner",
  "Sérum": "Serum",
  "Soin à l'huile": "Oil treatment",
  "Crème capillaire": "Hair cream",
  "Antipelliculaire": "Anti-dandruff",
  "Soin réparateur": "Repairing treatment",
  "Soin hydratant": "Moisturizing treatment",
  "Soin du cuir chevelu": "Scalp treatment",
  "Spray protecteur de chaleur": "Heat protection spray",
  "Soin en profondeur": "Deep conditioning",
  "Traitement à la kératine": "Keratin treatment",
  "Soin brillance / Patine": "Hair gloss",
  "Massage du cuir chevelu": "Scalp massage",
  "Détox capillaire": "Hair detox",
  "Soin protéiné": "Protein treatment",
  "Réparation des pointes fourchues": "Split-end repair",
  "Scellage des cuticules": "Cuticle sealing",
  "Soin spa pour cheveux": "Hair spa",
  "Neutralisation des reflets": "Toning",
  "Exfoliation du cuir chevelu": "Scalp exfoliation",
  "Lissage à la kératine": "Keratin treatment",
  "Lissage brésilien": "Brazilian blowout",
  "Lissage japonais": "Japanese straightening",
  "Lissage chimique": "Chemical straightening",
  "Défrisage": "Relaxer",
  "Fer à lisser": "Flat iron",
  "Lissage": "Straightening",
  "Lissage permanent": "Permanent straightening",
  "Coiffage à chaud": "Heat styling",
  "Lissage restructurant": "Rebonding",
  "Soin anti-frisottis": "Anti-frizz treatment",
  "Effet lissant": "Smooth effect",
  "Peigne": "Comb",
  "Brosse ronde": "Round brush",
  "Brosse plate": "Flat brush / paddle brush",
  "Peigne à larges dents": "Wide-tooth comb",
  "Peigne fin": "Fine-tooth comb",
  "Sèche-cheveux": "Hairdryer / blow dryer",
  "Fer à boucler": "Curling iron",
  "Pinces à cheveux": "Hair clips",
  "Pinces de séparation": "Sectioning clips",
  "Rouleaux": "Hair rollers",
  "Vaporisateur": "Spray bottle",
  "Ciseaux de coiffure": "Hair scissors",
  "Ciseaux sculpteurs / crantés": "Thinning scissors",
  "Élastiques": "Hair ties",
  "Épingles à cheveux": "Hairpins / bobby pins",
}

export const hairdressingDictionnaryFR = () => {
  return Object.keys(hairdressingDictionnaryEN).reduce((acc, key) => {
    acc[key] = key
    return acc
  }, {} as Record<string, string>)
}
